### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by BenRoe** [DHTN-KBD/build_your_own_planck_thk#1]
Hello,
i saw you have already build a planck thk. So maybe you can help me.
Can i use all the features (rotary encoder, dip switch) with the normal qmk planck firmware?
Or is there an extra qmk planck firmware?

BTW looking forward to you build guide. If it's ready, add it to my [awesome-mechanical-keyboard](https://github.com/BenRoe/awesome-mechanical-keyboard) list.

**Comment by juno** [comment]
> Can i use all the features (rotary encoder, dip switch) with the normal qmk planck firmware?
> Or is there an extra qmk planck firmware?

Unfortunately, no.
Planck THK support hasn't yet merged into master branch. So, you need to build firmware with planck_thk branch.
See: https://github.com/qmk/qmk_firmware/pull/4034

Also, at first you need to build bootloader (above PR contains it) and flash it. This requires AVR ISP devices such a Arduino.
Without bootloader, you can't flash firmware.

> BTW looking forward to you build guide. If it's ready, add it to my [awesome-mechanical-keyboard](https://github.com/BenRoe/awesome-mechanical-keyboard) list.

Sure.
After completed, I'll ping you. 😄
